name: authenticate-commits
env:
  TRUST_ROOT: 72e04ea3d99b6e268ae2366d739d7f5e26f319b0
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  authenticate-commits:
    runs-on: fedora-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Install sq-git
        run: dnf install -y sequoia-git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Authenticating commits
        run: sq-git log --trust-root $TRUST_ROOT
